server:
  port: 8080
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /

#springdoc:
#  remove-broken-reference-definitions: false
#  default-consumes-media-type: application/json
#  show-actuator: false
#  webjars:
#    prefix: /webjars
#  swagger-ui:
#    display-operation-id: true
#    display-request-duration: true
#    disable-swagger-default-url: true
#    deep-linking: true
#    try-it-out-enabled: false
#    persist-authorization: true
#    doc-expansion: none
#    default-models-expand-depth: 4
#    default-model-expand-depth: 4
#    groups-order: DESC
#    enabled: true
#    path: /swagger-ui
#    operations-sorter: alpha
#    tags-sorter: alpha
#
#  api-docs:
#    path: /api-docs
#    enabled: true
#    groups:
#      enabled: true

logging:
  level:
    root: INFO
    com.ydanneg: DEBUG

